# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .05
epsilon_anneal_time: 500000
mask_before_softmax: False

runner: "parallel"

buffer_size: 32
off_buffer_size: 70000 # size of the off-policy buffer default: 5000
batch_size_run: 10 # 10 num of parellel envs
batch_size: 16
off_batch_size: 32  # batch_size_train

env_args:
  state_last_action: True # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 600
step: 5 #steps for tree back up diagram  (adjustable based on # of agents)


lr: 0.0005
critic_lr: 0.0001
td_lambda: 0.8
icq_alpha: 0.1
icq_beta: 1000

# use qmix
mixing_embed_dim: 32

# use COMA
agent_output_type: "pi_logits"
learner: "offpg_learner"
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "ICQ-MA"

offline_dataset_dir: "/data/user/kouqian/SMAC410_pref_new/5m_vs_6m_good-medium_1000_30.th"
offline_dataset_quality: "good-medium"
pref_segment_pairs: 1000
use_pref: False

# for reward model learning & ICQ with reward_hat
train_reward: False
max_traj_length: 30
model_type: "NMR"
action_type: "Discrete"
reward_train_epoch: 100
reward_batch_size: 128
use_reward_hat: False